export const cities = [
    { name: 'Berlin', information: "Berlin[10][11] is the capital and largest city of Germany, both by area and by population.[12] Its more than 3.85 million inhabitants[13] make it the European Union's most populous city, as measured by population within city limits.[4] Simultaneously, the city is one of the states of Germany and is the third smallest state in the country in terms of area. Berlin is surrounded by the state of Brandenburg, and Brandenburg's capital Potsdam is nearby. The urban area of Berlin has a population of over 4.5 million and is therefore the most populous urban area in Germany.[5][14] The Berlin-Brandenburg capital region has around 6.2 million inhabitants and is Germany's second-largest metropolitan region after the Rhine-Ruhr region, and the fifth-biggest metropolitan region by GDP in the European Union", id: 1 },
    { name: 'London', information: "London is the capital and largest city of both England and the United Kingdom, with a population of around 8.8 million,[1] and its metropolitan area is the largest in Western Europe, with a population of 14.8 million.[9][note 1] It stands on the River Thames in south-east England at the head of a 50-mile (80 km) estuary down to the North Sea and has been a major settlement for nearly two millennia.[10] The City of London, its ancient core and financial centre, was founded by the Romans as Londinium and retains its medieval boundaries.", id: 2 },
    { name: 'Vancouver', information: "Vancouver (/vænˈkuːvər/ ⓘ van-KOO-vər) is a major city in western Canada, located in the Lower Mainland region of British Columbia. As the most populous city in the province, the 2021 Canadian census recorded 662,248 people in the city, up from 631,486 in 2016. The Metro Vancouver area had a population of 2.6 million in 2021, making it the third-largest metropolitan area in Canada. Greater Vancouver, along with the Fraser Valley, comprises the Lower Mainland with a regional population of over 3 million. Vancouver has the highest population density in Canada, with over 5,700 people per square kilometre,[6] and fourth highest in North America (after New York City, San Francisco, and Mexico City).", id: 3 },
    { name: 'New York', information: "New York, sometimes called New York State,[b] is a state in the Northeastern United States. One of the Mid-Atlantic states, it borders the Atlantic Ocean, New England, Canada and the Great Lakes.[c] With almost 19.6 million residents, it is the fourth-most populous state in the United States and eighth-most densely populated as of 2023.[5] New York is the 27th-largest U.S. state by area, with a total area of 54,556 square miles (141,300 km2", id: 4 },
]







